# Generated by Django 4.2.13 on 2024-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('community', models.CharField(max_length=100)),
                ('is_banned', models.BooleanField(default=0)),
                ('is_authenticated', models.BooleanField(default=0)),
                ('curr_auth_code', models.CharField(max_length=10)),
                ('requested_auth', models.BooleanField()),
            ],
        ),
    ]
