# Generated by Django 4.2.13 on 2024-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='hdjd@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_core',
            field=models.CharField(default='hdjd', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_provider',
            field=models.CharField(default='gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
