# Generated by Django 4.2.13 on 2024-06-02 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_community_user_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authenticated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
