# Generated by Django 4.2.13 on 2024-06-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_rename_community_user_community_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_name', models.CharField(max_length=100)),
                ('num_of_coordinates', models.IntegerField()),
                ('x_max', models.FloatField()),
                ('x_min', models.FloatField()),
                ('y_max', models.FloatField()),
                ('y_min', models.FloatField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_func.community')),
            ],
        ),
    ]
