# Generated by Django 4.2.13 on 2024-06-02 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_community_user_community_name'),
        ('core_func', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='plants_life',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_lat', models.FloatField()),
                ('plant_long', models.FloatField()),
                ('date_added', models.DateField(default=datetime.date(2024, 6, 2))),
                ('image', models.ImageField(upload_to='plants/')),
                ('is_a_plant', models.BooleanField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_func.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
