# Generated by Django 4.2.13 on 2024-06-02 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_func', '0002_community_plants_life_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 8, 11, 48, 229183, tzinfo=datetime.timezone.utc)),
        ),
    ]
