# Generated by Django 4.2.13 on 2024-06-02 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_func', '0003_alter_plant_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date_added',
            field=models.DateField(default=datetime.date(2024, 6, 2)),
        ),
    ]
